export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  GENERATOR: '/generator',
  TEMPLATES: '/templates',
  PROJECTS: '/projects',
  DOWNLOADS: '/downloads',
  AGENTS: '/agents',
  MARKETPLACE: '/marketplace',
  FAVORITES: '/favorites',
  SETTINGS: '/settings',
  HELP: '/help',
  ADMIN: '/admin',
  LOGIN: '/login',
  REGISTER: '/register',
  PROFILE: '/profile',
  BILLING: '/billing',
  HISTORY: '/history',
} as const;
